name: Validate Contribution Format

on:
  pull_request:
    paths:
      - 'data/names/**'  # Memantau semua perubahan dalam folder names

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Contribution Structure
        run: |
          # Memeriksa struktur folder
          for name_type in {1,2,3}; do
            if [ ! -d "data/names/$name_type" ]; then
              echo "Missing directory: data/names/$name_type"
              exit 1
            fi

            # Memeriksa apakah ada file JSON di dalam direktori
            if [ -z "$(ls -A data/names/$name_type/*.json 2>/dev/null)" ]; then
              echo "No JSON files found in: data/names/$name_type"
              exit 1
            fi

            # Validasi setiap file JSON
            for json_file in data/names/$name_type/*.json; do
              if ! jq empty "$json_file"; then
                echo "Invalid JSON format in $json_file"
                exit 1
              fi

              # Validasi struktur JSON
              expected_keys=("name" "name_type" "gender" "origin" "category" "contributor" "meaning")
              json_keys=$(jq -r 'keys[]' "$json_file")

              for key in "${expected_keys[@]}"; do
                if ! echo "$json_keys" | grep -q "$key"; then
                  echo "Missing expected key: $key in $json_file"
                  exit 1
                fi
              done
            done
          done

          echo "All checks passed."
