name: Anyname Lint

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Name and Name Type Format
        run: |
          for file in $(git diff --name-only origin/main | grep .md); do
            # Check if all required fields are present
            if ! grep -q -E "^# Child Name\n\n\*\*Name:\*\* .+\n\*\*Name Type:\*\* (1|2|3) word(s)?\n\*\*Gender:\*\* .+\n\*\*Origin:\*\* .+\n\*\*Meaning:\*\* .+\n\*\*Category:\*\* .+" $file; then
              echo "Invalid format in $file: missing or incorrect fields."
              exit 1
            fi

            # Extract Name and Name Type
            name=$(grep -E "\*\*Name:\*\*" $file | sed 's/\*\*Name:\*\* //' | tr -d '\n')
            name_type=$(grep -E "\*\*Name Type:\*\*" $file | sed 's/\*\*Name Type:\*\* //')

            # Count words in the name
            word_count=$(echo $name | wc -w)

            # Check if Name contains only letters (no numbers or special characters)
            if [[ ! "$name" =~ ^[a-zA-Z\ ]+$ ]]; then
              echo "Invalid Name in $file: Name contains invalid characters. Only letters are allowed."
              exit 1
            fi

            # Check if word count matches name type
            case $name_type in
              "1 word")
                if [ $word_count -ne 1 ]; then
                  echo "Invalid format in $file: Name should be 1 word, but found $word_count words."
                  exit 1
                fi
                ;;
              "2 words")
                if [ $word_count -ne 2 ]; then
                  echo "Invalid format in $file: Name should be 2 words, but found $word_count words."
                  exit 1
                fi
                ;;
              "3 words")
                if [ $word_count -ne 3 ]; then
                  echo "Invalid format in $file: Name should be 3 words, but found $word_count words."
                  exit 1
                fi
                ;;
              *)
                echo "Invalid Name Type in $file."
                exit 1
                ;;
            esac
          done
