name: Validate Contribution Format

on:
  pull_request:
    paths:
      - 'data/names/**'  # Memantau semua perubahan dalam folder names

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Contribution Structure
        id: validate
        run: |
          # Mengaktifkan nullglob agar wildcard tidak mengembalikan nama file jika tidak ada
          shopt -s nullglob

          validate_json() {
            local json_file="$1"
            # Validasi format JSON
            if ! jq empty "$json_file"; then
              echo "Invalid JSON format in $json_file"
              exit 1
            fi

            # Validasi struktur JSON
            expected_keys=("name" "name_type" "gender" "origin" "category" "contributor" "meaning")
            json_keys=$(jq -r 'keys[]' "$json_file")

            for key in "${expected_keys[@]}"; do
              if ! echo "$json_keys" | grep -q "$key"; then
                echo "Missing expected key: $key in $json_file"
                exit 1
              fi
            done
          }

          # Memeriksa struktur folder dan validasi setiap file JSON
          for name_type in {1,2,3}; do
            folder="data/names/$name_type"

            # Memeriksa apakah folder ada
            if [ ! -d "$folder" ]; then
              echo "Missing directory: $folder"
              exit 1
            fi

            # Memeriksa dan memvalidasi setiap file JSON di dalam direktori
            for json_file in "$folder"/*.json; do
              validate_json "$json_file"
            done
          done

          echo "All checks passed."

      - name: Add invalid label
        if: failure()  # Menjalankan langkah ini hanya jika validasi gagal
        uses: actions/github-script@v5
        with:
          script: |
            const { context } = require('@actions/github');
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            // Menambahkan label "invalid" pada pull request
            await github.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['invalid']
            });
