name: Label on Pull Requests

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            hacktoberfest
            opened
