name: Add Labels to Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is from a fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: echo "Pull request is from a fork."
      - name: Add labels if not from a fork
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            hacktoberfest
