name: Validate Names and Manage Labels

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Run validation
        id: validate_names
        run: |
          go run validator/validate_names.go
        continue-on-error: true 

      - name: Add label if invalid
        if: failure() # add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            invalid

      - name: Remove invalid label if fixed
        if: success() # remove label 
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            invalid
