name: Validate Names and Manage Labels

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Run validation
        id: validate_names
        run: |
          go run validator/validate_name.go
        continue-on-error: true  # Agar job tidak berhenti jika validasi gagal

      - name: Add label if invalid
        if: steps.validate_names.outcome == 'failure'  # Tambahkan label jika validasi gagal
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            invalid

      - name: Remove invalid label if fixed
        if: steps.validate_names.outcome == 'success'  # Hapus label jika validasi berhasil
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            invalid

      - name: Comment on pull request if invalid files found
        if: steps.validate_names.outcome == 'failure'  # Tambah komentar jika validasi gagal
        run: |
          echo "Invalid files found in this pull request:"
          echo "${{ steps.validate_names.outputs.validation_output }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"body": "Invalid files found:\n\n```text\n${{ steps.validate_names.outputs.validation_output }}\n```"}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
